name: Assignment Workflow

on:
  push:

jobs:

  python-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python Que.4/scraper.py

  csharp-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build Task 1 (Churros App)
        run: dotnet build Que.1/ChurrosApp/ChurrosApp.csproj

      - name: Build Task 2
        run: dotnet build Que.2/*.csproj